name: Auto test and deploy

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04]
        python: [3.7, 3.8]
    runs-on: ${{ matrix.os }}
    steps:
    - name: checkout code
      uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install django
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    - name: Test with django test unit
      run: python manage.py test

  deploy:
    needs: build
    runs-on: ubuntu-18.04
    steps:
    - name: Deploy to test server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.host }}
        username: root
        key: ${{ secrets.key }}
        script: cd software_test_with_ci && git pull
